info:
  contact: {}
paths:
  /example/helloworld:
    get:
      responses:
        "200":
          description: helloworld
          schema:
            type: string
      summary: ping example
swagger: "2.0"
